footer:
  framework: Framework
  themename: Theme

page:
  recent_posts: Recent Posts
  close_menu: Close Menu
  archives: Archives
  categories: Categories
  tags: Tags
  search: Search

sidebar:
  information: Information
  my_gossips: My gossips

